// src/components/Tooltip.tsx
import { autoUpdate, computePosition, offset, shift } from "@floating-ui/dom";
import React, { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import styles from "./UIFork.module.css";
import {
  registerTooltipHide,
  registerTooltipShow,
  shouldSkipDelay,
} from "../utils/tooltipManager";

interface TooltipProps {
  label: string;
  children: React.ReactElement;
  placement?: "top" | "bottom" | "left" | "right";
}

export function Tooltip({ label, children, placement = "top" }: TooltipProps) {
  const [isVisible, setIsVisible] = useState(false);
  const [position, setPosition] = useState({ x: 0, y: 0 });
  const triggerRef = useRef<HTMLElement | null>(null);
  const tooltipRef = useRef<HTMLDivElement | null>(null);
  const showTimeoutRef = useRef<NodeJS.Timeout | null>(null);
  const hideTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  useEffect(() => {
    if (!isVisible || !triggerRef.current || !tooltipRef.current) return;

    let cleanup: (() => void) | null = null;
    let cancelled = false;

    const updatePosition = async () => {
      if (cancelled || !triggerRef.current || !tooltipRef.current) return;
      try {
        const { x, y } = await computePosition(
          triggerRef.current,
          tooltipRef.current,
          {
            placement,
            strategy: "fixed",
            middleware: [offset(8), shift({ padding: 8 })],
          },
        );
        if (!cancelled) {
          setPosition({ x, y });
          if (tooltipRef.current) {
            tooltipRef.current.style.visibility = "visible";
            tooltipRef.current.classList.add(styles.tooltipVisible);
          }
        }
      } catch (error) {
        console.error("Error positioning tooltip:", error);
      }
    };

    // Initial positioning
    if (tooltipRef.current) {
      tooltipRef.current.style.visibility = "hidden";
    }
    updatePosition();

    // Auto-update position
    if (triggerRef.current && tooltipRef.current) {
      cleanup = autoUpdate(
        triggerRef.current,
        tooltipRef.current,
        updatePosition,
      );
    }

    return () => {
      cancelled = true;
      if (cleanup) cleanup();
      if (tooltipRef.current) {
        tooltipRef.current.classList.remove(styles.tooltipVisible);
      }
    };
  }, [isVisible, placement]);

  const handleMouseEnter = () => {
    // Clear any pending hide timeout (user is hovering again)
    if (hideTimeoutRef.current) {
      clearTimeout(hideTimeoutRef.current);
      hideTimeoutRef.current = null;
    }

    // Clear any pending show timeout
    if (showTimeoutRef.current) {
      clearTimeout(showTimeoutRef.current);
    }

    // Check if we should skip delay (another tooltip is visible or was recently shown)
    const skipDelay = shouldSkipDelay();
    const delay = skipDelay ? 0 : 300;

    // Show tooltip after delay (or immediately if skipping)
    showTimeoutRef.current = setTimeout(() => {
      setIsVisible(true);
      showTimeoutRef.current = null;
    }, delay);
  };

  const handleMouseLeave = () => {
    // Clear any pending show timeout
    if (showTimeoutRef.current) {
      clearTimeout(showTimeoutRef.current);
      showTimeoutRef.current = null;
    }

    // Add a delay before hiding to allow smooth handoff between tooltips
    hideTimeoutRef.current = setTimeout(() => {
      setIsVisible(false);
      registerTooltipHide();
      hideTimeoutRef.current = null;
    }, 150);
  };

  // Register/unregister tooltip visibility with global manager
  useEffect(() => {
    if (isVisible) {
      registerTooltipShow();
    } else {
      registerTooltipHide();
    }
  }, [isVisible]);

  // Cleanup timeouts on unmount
  useEffect(() => {
    return () => {
      if (showTimeoutRef.current) {
        clearTimeout(showTimeoutRef.current);
      }
      if (hideTimeoutRef.current) {
        clearTimeout(hideTimeoutRef.current);
      }
      if (isVisible) {
        registerTooltipHide();
      }
    };
  }, [isVisible]);

  // Clone the child element and add ref and event handlers
  const childWithProps = React.cloneElement(children, {
    ref: (node: HTMLElement | null) => {
      triggerRef.current = node;
      // Preserve original ref if it exists
      const originalRef = (children as any).ref;
      if (originalRef) {
        if (typeof originalRef === "function") {
          originalRef(node);
        } else {
          originalRef.current = node;
        }
      }
    },
    onMouseEnter: (e: React.MouseEvent) => {
      handleMouseEnter();
      children.props.onMouseEnter?.(e);
    },
    onMouseLeave: (e: React.MouseEvent) => {
      handleMouseLeave();
      children.props.onMouseLeave?.(e);
    },
  } as any);

  return (
    <>
      {childWithProps}
      {isVisible &&
        createPortal(
          <div
            ref={tooltipRef}
            className={styles.tooltip}
            style={{
              left: `${position.x}px`,
              top: `${position.y}px`,
              visibility: "hidden",
            }}
            role="tooltip"
          >
            {label}
          </div>,
          document.body,
        )}
    </>
  );
}

// packages/uifork-vue/src/components/Tooltip.vue
<script setup lang="ts">
import { ref, watch, onUnmounted, nextTick } from 'vue'
import { autoUpdate, computePosition, offset, shift } from '@floating-ui/dom'
import styles from './UIFork.module.css'
import { registerTooltipHide, registerTooltipShow, shouldSkipDelay } from '../utils/tooltipManager'

const props = defineProps<{
  label: string
  placement?: 'top' | 'bottom' | 'left' | 'right'
}>()

const isVisible = ref(false)
const position = ref({ x: 0, y: 0 })
const triggerRef = ref<HTMLElement | null>(null)
const tooltipRef = ref<HTMLDivElement | null>(null)
let showTimeout: ReturnType<typeof setTimeout> | null = null
let hideTimeout: ReturnType<typeof setTimeout> | null = null
let floatingCleanup: (() => void) | null = null

const placement = props.placement ?? 'top'

watch(isVisible, (visible) => {
  if (visible) {
    registerTooltipShow()
    nextTick(setupPositioning)
  } else {
    registerTooltipHide()
    if (floatingCleanup) {
      floatingCleanup()
      floatingCleanup = null
    }
  }
})

function setupPositioning() {
  if (!triggerRef.value || !tooltipRef.value) return
  if (floatingCleanup) floatingCleanup()

  const trigger = triggerRef.value
  const tooltip = tooltipRef.value
  tooltip.style.visibility = 'hidden'

  const updatePosition = async () => {
    if (!trigger || !tooltip) return
    try {
      const { x, y } = await computePosition(trigger, tooltip, {
        placement,
        strategy: 'fixed',
        middleware: [offset(8), shift({ padding: 8 })],
      })
      position.value = { x, y }
      tooltip.style.visibility = 'visible'
      tooltip.classList.add(styles.tooltipVisible)
    } catch {}
  }

  updatePosition()
  floatingCleanup = autoUpdate(trigger, tooltip, updatePosition)
}

function handleMouseEnter() {
  if (hideTimeout) { clearTimeout(hideTimeout); hideTimeout = null }
  if (showTimeout) clearTimeout(showTimeout)
  const skipDelay = shouldSkipDelay()
  showTimeout = setTimeout(() => {
    isVisible.value = true
    showTimeout = null
  }, skipDelay ? 0 : 300)
}

function handleMouseLeave() {
  if (showTimeout) { clearTimeout(showTimeout); showTimeout = null }
  hideTimeout = setTimeout(() => {
    isVisible.value = false
    hideTimeout = null
  }, 150)
}

onUnmounted(() => {
  if (showTimeout) clearTimeout(showTimeout)
  if (hideTimeout) clearTimeout(hideTimeout)
  if (floatingCleanup) floatingCleanup()
  if (isVisible.value) registerTooltipHide()
})
</script>

<template>
  <span
    ref="triggerRef"
    @mouseenter="handleMouseEnter"
    @mouseleave="handleMouseLeave"
    style="display: inline-flex"
  >
    <slot />
  </span>
  <Teleport to="#uifork-root" v-if="isVisible">
    <div
      ref="tooltipRef"
      :class="styles.tooltip"
      :style="{ left: `${position.x}px`, top: `${position.y}px`, visibility: 'hidden' }"
      role="tooltip"
    >
      {{ label }}
    </div>
  </Teleport>
</template>
