// packages/uifork/src/components/UIFork.tsx
"use client";

import React, { useCallback, useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { motion, AnimatePresence } from "motion/react";
import type { UIForkProps, VersionInfo } from "../types";
import styles from "./UIFork.module.css";
import { ComponentSelector, ComponentSelectorDropdown } from "./ComponentSelector";
import { VersionsList } from "./VersionsList";
import { SettingsView } from "./SettingsView";
import { EmptyStateNoComponents } from "./EmptyStateNoComponents";
import { NewVersionButton } from "./NewVersionButton";
import { OfflineMessage } from "./OfflineMessage";

// Custom hooks
import { useWebSocketConnection } from "../hooks/useWebSocketConnection";
import { useComponentDiscovery } from "../hooks/useComponentDiscovery";
import { useVersionManagement } from "../hooks/useVersionManagement";
import { usePopoverPosition } from "../hooks/usePopoverPosition";
import { useClickOutside } from "../hooks/useClickOutside";
import { useLocalStorage } from "../hooks/useLocalStorage";
import { useVersionKeyboardShortcuts, useDropdownKeyboard } from "../hooks/useKeyboardShortcuts";
import { useDragToCorner } from "../hooks/useDragToCorner";
import { useContainerPositioning } from "../hooks/useContainerPositioning";
import type { Position } from "../utils/positioning";
import { isDevelopment } from "../utils/environment";
import { ANIMATION_DURATION, ANIMATION_EASING } from "./constants";
import TriggerContent from "./TriggerContent";
import { ActiveView } from "./types";

/**
 * UIFork - A floating UI component that renders a version picker in the bottom right.
 * It communicates with the uifork watch server to manage component versions.
 *
 * Add this component to your app root (typically only in development):
 *
 * ```tsx
 * function App() {
 *   return (
 *     <>
 *       <YourApp />
 *       {process.env.NODE_ENV === "development" && <UIFork />}
 *     </>
 *   );
 * }
 * ```
 */
export function UIFork({ port = 3001, className = "", style }: UIForkProps) {
  const [isMounted, setIsMounted] = useState(false);

  // UI state
  const [isOpen, setIsOpen] = useState(false);
  const [isComponentSelectorOpen, setIsComponentSelectorOpen] = useState(false);
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);
  const [openPopoverVersion, setOpenPopoverVersion] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  // Root ref for theme wrapper
  const rootRef = useRef<HTMLDivElement | null>(null);

  // Refs
  const triggerRef = useRef<HTMLButtonElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const componentSelectorRef = useRef<HTMLDivElement>(null);
  const selectedComponentRef = useRef<string>("");

  // Settings
  const [theme, setTheme] = useLocalStorage<"light" | "dark" | "system">("uifork-theme", "system");
  const [position, setPosition] = useLocalStorage<Position>("uifork-position", "bottom-right");
  const [codeEditor, setCodeEditor] = useLocalStorage<"vscode" | "cursor">(
    "uifork-code-editor",
    "vscode",
  );
  // const [enableElementAwarePositioning, setEnableElementAwarePositioning] =
  //   useLocalStorage<boolean>("uifork-element-aware-positioning", false);

  // Container and component selector positioning hook
  const { containerPosition, transformOrigin, componentSelectorPosition } = useContainerPositioning(
    {
      position,
      isComponentSelectorOpen,
      containerRef,
      componentSelectorRef,
      // enableElementAwarePositioning,
    },
  );

  // Drag to corner hook
  const {
    isDragging,
    resetDrag,
    dragEnabled,
    dragControls,
    handlePointerDown,
    handleDragStart,
    handleDragEnd,
  } = useDragToCorner({
    isOpen,
    containerRef,
    setPosition,
  });

  // Component discovery hook
  const { mountedComponents, selectedComponent, setSelectedComponent, onComponentsUpdate } =
    useComponentDiscovery({ port });

  // Keep ref updated with current selected component
  useEffect(() => {
    selectedComponentRef.current = selectedComponent;
  }, [selectedComponent]);

  // Get current component's versions (includes labels)
  const currentComponent = mountedComponents.find((c) => c.name === selectedComponent);
  const versions: VersionInfo[] = currentComponent?.versions || [];

  // Helper to get label for a version key
  const getVersionLabel = (key: string): string | undefined => {
    return versions.find((v) => v.key === key)?.label;
  };

  // Version management hook
  const {
    activeVersion,
    setActiveVersion,
    editingVersion,
    renameValue,
    setRenameValue,
    startRename,
    confirmRename,
    cancelRename,
    clearEditingOnError,
    storePendingVersion,
    versionKeys,
  } = useVersionManagement({ selectedComponent, versions });

  // WebSocket connection hook
  const { connectionStatus, sendMessage } = useWebSocketConnection({
    port,
    selectedComponent,
    onComponentsUpdate,
    onVersionAck: ({ version, message, newVersion }) => {
      let versionToActivate: string | null = null;

      if (message?.includes("duplicated") || message?.includes("created new version")) {
        versionToActivate = version;
      } else if (message?.includes("renamed") && newVersion) {
        versionToActivate = newVersion;
      }

      if (versionToActivate) {
        storePendingVersion(versionToActivate);
      }
    },
    onPromoted: (promotedComponent) => {
      // Always check localStorage directly and remove if it matches the promoted component
      // This handles cases where state might be stale but localStorage has the value
      const storedValue = localStorage.getItem("uifork-selected-component");
      const storedComponent = storedValue ? JSON.parse(storedValue) : null;
      const currentSelected = selectedComponentRef.current;

      // Remove if either state or localStorage matches the promoted component
      if (currentSelected === promotedComponent || storedComponent === promotedComponent) {
        // Directly remove from localStorage immediately
        localStorage.removeItem("uifork-selected-component");
        // Clear state (hook should also handle removal, but we've already done it)
        setSelectedComponent("");
        // Aggressively ensure removal persists - check and remove multiple times
        const ensureRemoval = () => {
          const stored = localStorage.getItem("uifork-selected-component");
          if (stored) {
            try {
              const parsed = JSON.parse(stored);
              if (parsed === promotedComponent) {
                localStorage.removeItem("uifork-selected-component");
              }
            } catch {
              // If not JSON, check as plain string
              if (stored === promotedComponent) {
                localStorage.removeItem("uifork-selected-component");
              }
            }
          }
        };
        // Check immediately and after delays to handle any race conditions
        ensureRemoval();
        setTimeout(ensureRemoval, 0);
        setTimeout(ensureRemoval, 50);
        setTimeout(ensureRemoval, 100);
      }
      // Components will be updated automatically via WebSocket
    },
    onError: clearEditingOnError,
  });

  // Popover positioning hook
  const { popoverPositions, setPopoverTriggerRef, setPopoverDropdownRef } = usePopoverPosition({
    openPopoverVersion,
  });

  // Keyboard shortcuts for version switching
  useVersionKeyboardShortcuts({
    versionKeys,
    activeVersion,
    setActiveVersion,
  });

  // Dropdown keyboard navigation
  useDropdownKeyboard({
    isOpen,
    containerRef,
    triggerRef,
    openPopoverVersion,
    isComponentSelectorOpen,
    editingVersion,
    onClosePopover: () => setOpenPopoverVersion(null),
    onCloseComponentSelector: () => setIsComponentSelectorOpen(false),
    onCancelRename: cancelRename,
    onClose: () => {
      setIsOpen(false);
      setIsSettingsOpen(false);
    },
  });

  // Click outside handling for main dropdown
  // Note: ComponentSelectorDropdown and VersionActionMenu handle their own click-outside
  useClickOutside({
    isActive: isOpen,
    refs: [triggerRef, containerRef],
    onClickOutside: useCallback(() => {
      if (editingVersion) {
        cancelRename();
      }
      setIsOpen(false);
      setIsSettingsOpen(false);
      setIsComponentSelectorOpen(false);
    }, [editingVersion, cancelRename]),
    additionalCheck: useCallback((target: Node) => {
      // Check if clicking inside component selector dropdown (portaled outside container)
      if (componentSelectorRef.current?.contains(target)) {
        return true;
      }
      // Check if clicking inside popover elements (portaled outside container)
      const popoverElements = document.querySelectorAll("[data-popover-dropdown]");
      for (const el of popoverElements) {
        if (el.contains(target)) return true;
      }
      return false;
    }, []),
  });

  // Mount effect
  useEffect(() => {
    setIsMounted(true);
  }, []);

  // Action handlers
  const handleDuplicateVersion = (version: string, e: React.MouseEvent) => {
    e.stopPropagation();
    sendMessage("duplicate_version", { version });
  };

  const handleDeleteVersion = (version: string, e: React.MouseEvent) => {
    e.stopPropagation();
    sendMessage("delete_version", { version });
  };

  const handleNewVersion = (e: React.MouseEvent) => {
    e.stopPropagation();
    sendMessage("new_version", {});
  };

  const handleRenameVersion = (version: string, e: React.MouseEvent) => {
    e.stopPropagation();
    startRename(version);
  };

  const handleConfirmRename = useCallback(
    (version: string) => {
      const newLabel = confirmRename(version);
      if (newLabel !== null) {
        sendMessage("rename_label", {
          version,
          newLabel,
        });
      }
    },
    [confirmRename, sendMessage],
  );

  const handlePromoteVersion = (version: string, e: React.MouseEvent) => {
    e.stopPropagation();
    const label = getVersionLabel(version) || formatVersionLabel(version);
    if (
      window.confirm(
        `Are you sure you want to promote version ${label}?\n\nThis will:\n- Replace the main component with this version\n- Remove all versioning scaffolding\n- This action cannot be undone`,
      )
    ) {
      sendMessage("promote_version", { version });
      setOpenPopoverVersion(null);
    }
  };

  const handleTogglePopover = (version: string, e?: React.MouseEvent) => {
    e?.stopPropagation();
    setOpenPopoverVersion(openPopoverVersion === version ? null : version);
  };

  const handleOpenInEditor = async (version: string, e: React.MouseEvent) => {
    e.stopPropagation();
    try {
      const response = await fetch(`http://localhost:${port}/open-in-editor`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          version,
          component: selectedComponent,
          editor: codeEditor,
        }),
      });
      if (!response.ok) {
        await response.json();
      }
    } catch {
      // Error opening in editor
    }
    setOpenPopoverVersion(null);
  };

  // Format version label (v1 -> V1, v1_2 -> V1.2)
  const formatVersionLabel = (version: string) => {
    return version.replace(/^v/, "V").replace(/_/g, ".");
  };

  // Copy command to clipboard
  const handleCopyCommand = useCallback(async () => {
    const command = "npx uifork init ";
    try {
      await navigator.clipboard.writeText(command);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Failed to copy command
    }
  }, []);

  // Create or get root element for theming
  useEffect(() => {
    if (!isMounted) return;

    let rootEl = document.getElementById("uifork-root") as HTMLDivElement | null;
    if (!rootEl) {
      rootEl = document.createElement("div");
      rootEl.id = "uifork-root";
      rootEl.className = styles.uiforkRoot || "uiforkRoot";
      document.body.appendChild(rootEl);
    }
    rootRef.current = rootEl;

    // Update theme attribute
    rootEl.setAttribute("data-theme", theme);

    return () => {
      // Don't remove root element on unmount as it might be used by other instances
    };
  }, [isMounted, theme, styles]);

  // Determine if we're connected to the WebSocket server
  const isConnected = connectionStatus === "connected";

  // Determine active view based on current state
  const activeView: ActiveView = React.useMemo(() => {
    if (!isOpen) {
      // When closed, determine if we show icon-only or icon+label
      const hasComponents = mountedComponents.length > 0;

      // Show icon+label when has components (works offline too now)
      if (hasComponents) {
        return "closed-trigger-label";
      }

      // Otherwise show icon-only (connecting or no components)
      return "closed-trigger-icon";
    }

    // When dropdown is open, determine which view to show
    if (isSettingsOpen) {
      return "opened-settings";
    }

    if (mountedComponents.length === 0) {
      return "opened-no-components";
    }

    // Show version list even when disconnected - actions will be disabled
    return "opened-version-list";
  }, [isOpen, isSettingsOpen, mountedComponents.length]);

  // Don't render until mounted on client (prevents hydration mismatch)
  if (!isMounted) {
    return null;
  }

  const portalRoot = rootRef.current || document.getElementById("uifork-root");
  if (!portalRoot) {
    return null;
  }

  return createPortal(
    <>
      <motion.div
        ref={containerRef}
        className={`${styles.container} ${!isOpen ? styles.containerClosed : ""} ${className}`}
        layout
        drag={dragEnabled && !isOpen}
        dragControls={dragControls}
        dragMomentum={false}
        dragElastic={0}
        dragListener={false}
        onPointerDown={handlePointerDown}
        onDragStart={handleDragStart}
        onDragEnd={handleDragEnd}
        animate={resetDrag ? { x: 0, y: 0 } : {}}
        style={{
          borderRadius: isOpen ? 12 : 20,
          boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
          ...containerPosition,
          transformOrigin,
          // Don't set cursor here - we handle it on document.body to override CSS
          touchAction: !isOpen ? "none" : "auto",
          ...style,
        }}
        transition={{
          layout: {
            duration: ANIMATION_DURATION,
            ease: ANIMATION_EASING,
          },
          x: {
            duration: ANIMATION_DURATION,
            ease: ANIMATION_EASING,
          },
          y: {
            duration: ANIMATION_DURATION,
            ease: ANIMATION_EASING,
          },
        }}
      >
        <AnimatePresence mode="popLayout" initial={false}>
          {activeView === "closed-trigger-icon" || activeView === "closed-trigger-label" ? (
            <motion.button
              key="trigger"
              suppressHydrationWarning
              ref={triggerRef}
              onClick={(e) => {
                // Prevent opening if we just finished dragging
                if (isDragging) {
                  e.preventDefault();
                  return;
                }
                setIsOpen(true);
                setIsSettingsOpen(false);
              }}
              aria-label="Select UI version"
              aria-expanded={false}
              aria-haspopup="listbox"
              className={`${styles.trigger} ${
                activeView === "closed-trigger-icon" ? styles.triggerIconOnly : ""
              }`}
              layout
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{
                duration: ANIMATION_DURATION,
                ease: ANIMATION_EASING,
              }}
              draggable={false}
            >
              <TriggerContent
                activeView={activeView}
                connectionStatus={connectionStatus}
                selectedComponent={selectedComponent}
                activeVersion={activeVersion}
                activeVersionLabel={getVersionLabel(activeVersion)}
                formatVersionLabel={formatVersionLabel}
                isConnected={isConnected}
              />
            </motion.button>
          ) : (
            <motion.div
              key="dropdown"
              ref={dropdownRef}
              role="listbox"
              aria-label="UI version options"
              className={styles.dropdown}
              layout
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{
                duration: ANIMATION_DURATION,
                ease: ANIMATION_EASING,
              }}
            >
              {activeView === "opened-no-components" && (
                <EmptyStateNoComponents onCopyCommand={handleCopyCommand} copied={copied} />
              )}

              {activeView === "opened-settings" && (
                <SettingsView
                  onBack={() => setIsSettingsOpen(false)}
                  theme={theme}
                  setTheme={setTheme}
                  position={position}
                  setPosition={setPosition}
                  codeEditor={codeEditor}
                  setCodeEditor={setCodeEditor}
                  // enableElementAwarePositioning={enableElementAwarePositioning}
                  // setEnableElementAwarePositioning={setEnableElementAwarePositioning}
                />
              )}

              {activeView === "opened-version-list" && (
                <>
                  {/* Component selector */}
                  <ComponentSelector
                    selectedComponent={selectedComponent}
                    onToggle={() => setIsComponentSelectorOpen(!isComponentSelectorOpen)}
                    onSettingsClick={(e) => {
                      e.stopPropagation();
                      setIsSettingsOpen(true);
                    }}
                  />

                  <div className={styles.divider} />

                  {/* Versions list */}
                  <VersionsList
                    versions={versions}
                    activeVersion={activeVersion}
                    editingVersion={editingVersion}
                    renameValue={renameValue}
                    formatVersionLabel={formatVersionLabel}
                    openPopoverVersion={openPopoverVersion}
                    popoverPositions={popoverPositions}
                    isConnected={isConnected}
                    onSelectVersion={(version) => {
                      setActiveVersion(version);
                    }}
                    onDuplicateVersion={handleDuplicateVersion}
                    onTogglePopover={handleTogglePopover}
                    onPromoteVersion={handlePromoteVersion}
                    onOpenInEditor={handleOpenInEditor}
                    onDeleteVersion={handleDeleteVersion}
                    onRenameVersion={handleRenameVersion}
                    onRenameValueChange={setRenameValue}
                    onConfirmRename={handleConfirmRename}
                    onCancelRename={cancelRename}
                    setPopoverTriggerRef={setPopoverTriggerRef}
                    setPopoverDropdownRef={setPopoverDropdownRef}
                  />

                  {isDevelopment() && (
                    <>
                      <div className={styles.divider} />

                      {/* New version button or offline message */}
                      {isConnected ? (
                        <NewVersionButton onClick={handleNewVersion} />
                      ) : (
                        <OfflineMessage />
                      )}
                    </>
                  )}
                </>
              )}
            </motion.div>
          )}
        </AnimatePresence>
      </motion.div>
      {/* Component selector dropdown */}
      {activeView !== "closed-trigger-icon" && activeView !== "closed-trigger-label" && (
        <ComponentSelectorDropdown
          mountedComponents={mountedComponents}
          selectedComponent={selectedComponent}
          isOpen={isComponentSelectorOpen}
          position={componentSelectorPosition}
          onSelect={(componentName) => {
            setSelectedComponent(componentName);
            setIsComponentSelectorOpen(false);
          }}
          onClose={() => setIsComponentSelectorOpen(false)}
          componentSelectorRef={componentSelectorRef}
          isConnected={isConnected}
        />
      )}
    </>,
    portalRoot,
  );
}

// packages/uifork-vue/src/components/UIFork.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted, nextTick } from 'vue'
import type { UIForkProps, VersionInfo } from '../types'
import type { ActiveView } from '../types'
import styles from './UIFork.module.css'
import ComponentSelector from './ComponentSelector.vue'
import VersionsList from './VersionsList.vue'
import SettingsView from './SettingsView.vue'
import EmptyStateNoComponents from './EmptyStateNoComponents.vue'
import NewVersionButton from './NewVersionButton.vue'
import OfflineMessage from './OfflineMessage.vue'
import TriggerContent from './TriggerContent.vue'
import ChevronRightIcon from './icons/ChevronRightIcon.vue'
import CheckmarkIcon from './icons/CheckmarkIcon.vue'
import InfoIcon from './icons/InfoIcon.vue'

import { useWebSocketConnection } from '../composables/useWebSocketConnection'
import { useComponentDiscovery } from '../composables/useComponentDiscovery'
import { useVersionManagement } from '../composables/useVersionManagement'
import { usePopoverPosition } from '../composables/usePopoverPosition'
import { useClickOutside } from '../composables/useClickOutside'
import { useLocalStorage } from '../composables/useLocalStorage'
import { useVersionKeyboardShortcuts, useDropdownKeyboard } from '../composables/useKeyboardShortcuts'
import { useDragToCorner } from '../composables/useDragToCorner'
import { useContainerPositioning } from '../composables/useContainerPositioning'
import type { Position } from '../utils/positioning'
import { isDevelopment } from '../utils/environment'
import { getParentInfo, isComponentMounted } from '../utils/componentRegistry'

const props = withDefaults(defineProps<UIForkProps>(), {
  port: 3030,
  className: '',
})

const isMounted = ref(false)

// UI state
const isOpen = ref(false)
const isComponentSelectorOpen = ref(false)
const isSettingsOpen = ref(false)
const openPopoverVersion = ref<string | null>(null)
const copied = ref(false)

// Refs
const rootRef = ref<HTMLDivElement | null>(null)
const triggerRef = ref<HTMLButtonElement | null>(null)
const containerRef = ref<HTMLDivElement | null>(null)
const dropdownRef = ref<HTMLDivElement | null>(null)
// Settings
const [theme, setTheme] = useLocalStorage<'light' | 'dark' | 'system'>('uifork-theme', 'system')
const [position, setPosition] = useLocalStorage<Position>('uifork-position', 'bottom-right')
const [codeEditor, setCodeEditor] = useLocalStorage<'vscode' | 'cursor'>('uifork-code-editor', 'vscode')

// Container positioning
const { containerPosition, transformOrigin } = useContainerPositioning({
  position,
  isComponentSelectorOpen,
  containerRef,
})

// Drag to corner
const { isDragging, resetDrag, handlePointerDown } = useDragToCorner({
  isOpen,
  containerRef,
  setPosition,
})

// Component discovery
const { mountedComponents, allKnownComponents, selectedComponent, setSelectedComponent, onComponentsUpdate } =
  useComponentDiscovery({ port: props.port })

// Current component versions — use allKnownComponents so we can show versions
// even for components not currently mounted (e.g. ContactCard inside HomePage.v1)
const currentComponent = computed(() =>
  allKnownComponents.value.find((c) => c.name === selectedComponent.value),
)
const versions = computed<VersionInfo[]>(() => currentComponent.value?.versions || [])

const getVersionLabel = (key: string): string | undefined =>
  versions.value.find((v) => v.key === key)?.label

const COMPONENT_VERSION_STORAGE_PREFIX = 'uifork-component-'

// Smart switching: when selecting a component that's not mounted,
// auto-switch its parent to the version that contains it
watch(selectedComponent, (componentName) => {
  if (!componentName) return
  if (isComponentMounted(componentName)) return

  const parentInfo = getParentInfo(componentName)
  if (!parentInfo) return

  // Switch the parent to the version that contains this child
  const parentKey = `${COMPONENT_VERSION_STORAGE_PREFIX}${parentInfo.id}`
  const parentVersion = JSON.stringify(parentInfo.version)
  window.localStorage.setItem(parentKey, parentVersion)
  window.dispatchEvent(
    new StorageEvent('storage', { key: parentKey, newValue: parentVersion }),
  )
})

// Version management
const {
  activeVersion,
  setActiveVersion,
  editingVersion,
  renameValue,
  startRename,
  confirmRename,
  cancelRename,
  clearEditingOnError,
  storePendingVersion,
  versionKeys,
} = useVersionManagement({
  selectedComponent: () => selectedComponent.value,
  versions: () => versions.value,
})

// WebSocket
const { connectionStatus, sendMessage } = useWebSocketConnection({
  port: props.port,
  selectedComponent: () => selectedComponent.value,
  onComponentsUpdate,
  onVersionAck: ({ version, message, newVersion }) => {
    let versionToActivate: string | null = null
    if (message?.includes('duplicated') || message?.includes('created new version')) {
      versionToActivate = version
    } else if (message?.includes('renamed') && newVersion) {
      versionToActivate = newVersion
    }
    if (versionToActivate) storePendingVersion(versionToActivate)
  },
  onPromoted: (promotedComponent) => {
    const storedValue = localStorage.getItem('uifork-selected-component')
    const storedComponent = storedValue ? JSON.parse(storedValue) : null
    const currentSelected = selectedComponent.value

    if (currentSelected === promotedComponent || storedComponent === promotedComponent) {
      localStorage.removeItem('uifork-selected-component')
      setSelectedComponent('')
      const ensureRemoval = () => {
        const stored = localStorage.getItem('uifork-selected-component')
        if (stored) {
          try {
            const parsed = JSON.parse(stored)
            if (parsed === promotedComponent) localStorage.removeItem('uifork-selected-component')
          } catch {
            if (stored === promotedComponent) localStorage.removeItem('uifork-selected-component')
          }
        }
      }
      ensureRemoval()
      setTimeout(ensureRemoval, 0)
      setTimeout(ensureRemoval, 50)
      setTimeout(ensureRemoval, 100)
    }
  },
  onError: clearEditingOnError,
})

// Popover positioning
const { popoverPositions, setPopoverTriggerRef, setPopoverDropdownRef } = usePopoverPosition({
  openPopoverVersion,
})

// Keyboard shortcuts
useVersionKeyboardShortcuts({
  versionKeys: () => versionKeys.value,
  activeVersion,
  setActiveVersion,
  mountedComponents: () => mountedComponents.value,
  selectedComponent,
  setSelectedComponent,
})

useDropdownKeyboard({
  isOpen,
  triggerRef,
  openPopoverVersion,
  isComponentSelectorOpen,
  editingVersion,
  onClosePopover: () => (openPopoverVersion.value = null),
  onCloseComponentSelector: () => (isComponentSelectorOpen.value = false),
  onCancelRename: cancelRename,
  onClose: () => {
    isOpen.value = false
    isSettingsOpen.value = false
  },
})

// Click outside
useClickOutside({
  isActive: isOpen,
  refs: [triggerRef, containerRef],
  onClickOutside: () => {
    if (editingVersion.value) cancelRename()
    isOpen.value = false
    isSettingsOpen.value = false
    isComponentSelectorOpen.value = false
  },
  additionalCheck: (target: Node) => {
    const popoverElements = document.querySelectorAll('[data-popover-dropdown]')
    for (const el of popoverElements) {
      if (el.contains(target)) return true
    }
    return false
  },
})

// Mount effect - create root element
onMounted(() => {
  isMounted.value = true
  nextTick(() => {
    let rootEl = document.getElementById('uifork-root') as HTMLDivElement | null
    if (!rootEl) {
      rootEl = document.createElement('div')
      rootEl.id = 'uifork-root'
      rootEl.className = styles.uiforkRoot || 'uiforkRoot'
      document.body.appendChild(rootEl)
    }
    rootRef.value = rootEl
    rootEl.setAttribute('data-theme', theme.value)
  })
})

// Update theme
watch(theme, (t) => {
  const rootEl = document.getElementById('uifork-root')
  if (rootEl) rootEl.setAttribute('data-theme', t)
})

const isConnected = computed(() => connectionStatus.value === 'connected')

// Active view
const activeView = computed<ActiveView>(() => {
  if (!isOpen.value) {
    const hasComponents = allKnownComponents.value.length > 0
    return hasComponents ? 'closed-trigger-label' : 'closed-trigger-icon'
  }
  if (isComponentSelectorOpen.value) return 'opened-component-selector'
  if (isSettingsOpen.value) return 'opened-settings'
  if (allKnownComponents.value.length === 0) return 'opened-no-components'
  return 'opened-version-list'
})

// Action handlers
function handleDuplicateVersion(version: string, e: MouseEvent) {
  e.stopPropagation()
  sendMessage('duplicate_version', { version })
}

function handleDeleteVersion(version: string, e: MouseEvent) {
  e.stopPropagation()
  sendMessage('delete_version', { version })
}

function handleNewVersion(e: MouseEvent) {
  e.stopPropagation()
  sendMessage('new_version', {})
}

function handleRenameVersion(version: string, e: MouseEvent) {
  e.stopPropagation()
  startRename(version)
}

function handleConfirmRename(version: string) {
  const newLabel = confirmRename(version)
  if (newLabel !== null) {
    sendMessage('rename_label', { version, newLabel })
  }
}

function handlePromoteVersion(version: string, e: MouseEvent) {
  e.stopPropagation()
  const label = getVersionLabel(version) || formatVersionLabel(version)
  if (
    window.confirm(
      `Are you sure you want to promote version ${label}?\n\nThis will:\n- Replace the main component with this version\n- Remove all versioning scaffolding\n- This action cannot be undone`,
    )
  ) {
    sendMessage('promote_version', { version })
    openPopoverVersion.value = null
  }
}

function handleTogglePopover(version: string, e?: MouseEvent) {
  e?.stopPropagation()
  openPopoverVersion.value = openPopoverVersion.value === version ? null : version
}

async function handleOpenInEditor(version: string, e: MouseEvent) {
  e.stopPropagation()
  try {
    const response = await fetch(`http://localhost:${props.port}/open-in-editor`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        version,
        component: selectedComponent.value,
        editor: codeEditor.value,
      }),
    })
    if (!response.ok) await response.json()
  } catch {
    // Error opening in editor
  }
  openPopoverVersion.value = null
}

function formatVersionLabel(version: string) {
  return version.replace(/^v/, 'V').replace(/_/g, '.')
}

async function handleCopyCommand() {
  const command = 'npx uifork-vue  '
  try {
    await navigator.clipboard.writeText(command)
    copied.value = true
    setTimeout(() => (copied.value = false), 2000)
  } catch {
    // Failed to copy
  }
}

function handleTriggerClick(e: MouseEvent) {
  if (isDragging.value) {
    e.preventDefault()
    return
  }
  isOpen.value = true
  isSettingsOpen.value = false
}
</script>

<template>
  <Teleport to="#uifork-root" v-if="isMounted && rootRef">
    <div
      ref="containerRef"
      :class="[styles.container, !isOpen ? styles.containerClosed : '', props.className]"
      :style="{
        borderRadius: isOpen ? '12px' : '16px',
        boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        ...containerPosition,
        transformOrigin,
        touchAction: !isOpen ? 'none' : 'auto',
        transition: 'border-radius 0.3s cubic-bezier(0.04, 1.02, 0.13, 1.02), top 0.3s cubic-bezier(0.04, 1.02, 0.13, 1.02), right 0.3s cubic-bezier(0.04, 1.02, 0.13, 1.02), bottom 0.3s cubic-bezier(0.04, 1.02, 0.13, 1.02), left 0.3s cubic-bezier(0.04, 1.02, 0.13, 1.02)',
        ...props.style,
      }"
      @pointerdown="handlePointerDown"
    >
      <!-- Closed trigger -->
      <button
        v-if="activeView === 'closed-trigger-icon' || activeView === 'closed-trigger-label'"
        ref="triggerRef"
        @click="handleTriggerClick"
        aria-label="Select UI version"
        :aria-expanded="false"
        aria-haspopup="listbox"
        :class="[
          styles.trigger,
          !selectedComponent || versions.length === 0 ? styles.triggerIconOnly : '',
        ]"
        :draggable="false"
      >
        <TriggerContent
          :has-selection="!!selectedComponent && versions.length > 0"
          :selected-component="selectedComponent"
          :active-version="activeVersion"
          :active-version-label="getVersionLabel(activeVersion)"
          :format-version-label="formatVersionLabel"
        />
      </button>

      <!-- Open dropdown -->
      <div
        v-else
        ref="dropdownRef"
        role="listbox"
        aria-label="UI version options"
        :class="styles.dropdown"
      >
        <EmptyStateNoComponents
          v-if="activeView === 'opened-no-components'"
          :copied="copied"
          @copy-command="handleCopyCommand"
        />

        <SettingsView
          v-if="activeView === 'opened-settings'"
          :theme="theme"
          :position="position"
          :code-editor="codeEditor"
          @back="isSettingsOpen = false"
          @update:theme="setTheme"
          @update:position="setPosition"
          @update:code-editor="setCodeEditor"
        />

        <!-- Inline component selector (like settings) -->
        <div v-if="activeView === 'opened-component-selector'" :class="styles.settingsView">
          <button
            @click="isComponentSelectorOpen = false"
            :class="styles.settingsBackButton"
            :style="{ width: 'auto', alignSelf: 'flex-start' }"
          >
            <ChevronRightIcon :class="styles.settingsBackIcon" />
            <span>Back</span>
          </button>
          <div :class="styles.componentSelectorDropdownTitle" :style="{ padding: '4px 8px' }">Forked components</div>
          <div :style="{ display: 'flex', flexDirection: 'column', gap: '2px', padding: '0 4px' }">
            <button
              v-for="component in allKnownComponents"
              :key="component.name"
              @click="setSelectedComponent(component.name); isComponentSelectorOpen = false"
              :class="[
                styles.componentSelectorItem,
                styles.menuItem,
                component.name === selectedComponent ? styles.componentSelectorItemSelected : '',
              ]"
            >
              <div :class="styles.componentSelectorItemCheckmarkContainer">
                <CheckmarkIcon v-if="component.name === selectedComponent" :class="styles.componentSelectorItemCheckmark" />
              </div>
              <span :class="styles.componentSelectorItemName">{{ component.name }}</span>
              <span :class="styles.componentSelectorItemCount">{{ component.versions.length }}</span>
            </button>
          </div>
          <div v-if="isConnected" :class="styles.componentSelectorDropdownHint" :style="{ padding: '8px 12px' }">
            <InfoIcon :class="styles.componentSelectorDropdownHintIcon" />
            <span>
              Use <code :class="styles.componentSelectorDropdownHintCode">npx uifork-vue init</code> to
              iterate on more components
            </span>
          </div>
        </div>

        <template v-if="activeView === 'opened-version-list'">
          <ComponentSelector
            :selected-component="selectedComponent"
            @toggle="isComponentSelectorOpen = !isComponentSelectorOpen"
            @settings-click="(e: MouseEvent) => { e.stopPropagation(); isSettingsOpen = true }"
          />

          <div :class="styles.divider" />

          <VersionsList
            :versions="versions"
            :active-version="activeVersion"
            :editing-version="editingVersion"
            :rename-value="renameValue"
            :format-version-label="formatVersionLabel"
            :open-popover-version="openPopoverVersion"
            :popover-positions="popoverPositions"
            :is-connected="isConnected"
            @select-version="(v: string) => setActiveVersion(v)"
            @duplicate-version="handleDuplicateVersion"
            @toggle-popover="handleTogglePopover"
            @promote-version="handlePromoteVersion"
            @open-in-editor="handleOpenInEditor"
            @delete-version="handleDeleteVersion"
            @rename-version="handleRenameVersion"
            @rename-value-change="(v: string) => (renameValue = v)"
            @confirm-rename="handleConfirmRename"
            @cancel-rename="cancelRename"
            @set-popover-trigger-ref="setPopoverTriggerRef"
            @set-popover-dropdown-ref="setPopoverDropdownRef"
          />

          <template v-if="isDevelopment()">
            <div :class="styles.divider" />
            <NewVersionButton v-if="isConnected" @click="handleNewVersion" />
            <OfflineMessage v-else />
          </template>
        </template>
      </div>
    </div>

  </Teleport>
</template>
