// packages/uifork/src/components/VersionActionMenu.tsx
import React, { useRef, useCallback } from "react";
import { createPortal } from "react-dom";
import styles from "./UIFork.module.css";
import { PromoteIcon } from "./icons/PromoteIcon";
import { OpenInEditorIcon } from "./icons/OpenInEditorIcon";
import { DeleteIcon } from "./icons/DeleteIcon";
import { RenameIcon } from "./icons/RenameIcon";
import { MenuItem } from "./MenuItem";
import { useClickOutside } from "../hooks/useClickOutside";

interface VersionActionMenuProps {
  version: string;
  label?: string;
  position: { x: number; y: number };
  onPromote: (version: string, e: React.MouseEvent) => void;
  onOpenInEditor: (version: string, e: React.MouseEvent) => void;
  onDelete: (version: string, e: React.MouseEvent) => void;
  onRename: (version: string, e: React.MouseEvent) => void;
  onClose: () => void;
  setDropdownRef: (el: HTMLDivElement | null) => void;
}

export function VersionActionMenu({
  version,
  label,
  position: _position,
  onPromote,
  onOpenInEditor,
  onDelete,
  onRename,
  onClose,
  setDropdownRef,
}: VersionActionMenuProps) {
  const renameLabel = label && label.trim() ? "Edit label" : "Add label";
  const dropdownRef = useRef<HTMLDivElement>(null);

  // Combine local ref with callback ref from parent
  const combinedRef = useCallback(
    (el: HTMLDivElement | null) => {
      (dropdownRef as React.MutableRefObject<HTMLDivElement | null>).current = el;
      setDropdownRef(el);
    },
    [setDropdownRef],
  );

  // Close menu when clicking outside
  useClickOutside({
    isActive: true,
    refs: [dropdownRef],
    onClickOutside: onClose,
    // Don't close when clicking the trigger button (it handles its own toggle)
    additionalCheck: (target) => {
      const element = target as Element;
      // Check if clicking inside the actions area (which contains the trigger)
      return !!element.closest?.("[data-actions]");
    },
  });

  // Get the root wrapper element so we portal into it for theme inheritance
  const rootElement =
    typeof document !== "undefined"
      ? document.getElementById("uifork-root") || document.body
      : null;

  if (!rootElement) {
    return null;
  }

  // Don't set position via props - the positioning effect handles it directly
  // This prevents the popover from flashing at (0, 0) on initial render
  // The CSS animation will handle the fade-in and scale effect
  // Render in a portal to escape the scroll container and allow overflow
  return createPortal(
    <div
      ref={combinedRef}
      className={styles.popover}
      data-popover-dropdown
      style={{
        visibility: "hidden",
      }}
      role="menu"
    >
      <MenuItem
        icon={RenameIcon}
        label={renameLabel}
        stopPropagation
        onClick={(e) => {
          onRename(version, e);
          onClose();
        }}
      />
      <MenuItem
        icon={PromoteIcon}
        label="Promote"
        onClick={(e) => {
          onPromote(version, e);
          onClose();
        }}
      />
      <MenuItem
        icon={OpenInEditorIcon}
        label="Open in editor"
        onClick={(e) => {
          onOpenInEditor(version, e);
          onClose();
        }}
      />
      <div className={styles.divider} />
      <MenuItem
        icon={DeleteIcon}
        label="Delete"
        variant="delete"
        stopPropagation
        onClick={(e) => {
          onDelete(version, e);
          onClose();
        }}
      />
    </div>,
    rootElement,
  );
}

// packages/uifork-vue/src/components/VersionActionMenu.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import styles from './UIFork.module.css'
import PromoteIcon from './icons/PromoteIcon.vue'
import OpenInEditorIcon from './icons/OpenInEditorIcon.vue'
import DeleteIcon from './icons/DeleteIcon.vue'
import RenameIcon from './icons/RenameIcon.vue'
import MenuItem from './MenuItem.vue'
import { useClickOutside } from '../composables/useClickOutside'

const props = defineProps<{
  version: string
  label?: string
}>()

const emit = defineEmits<{
  promote: [version: string, e: MouseEvent]
  openInEditor: [version: string, e: MouseEvent]
  delete: [version: string, e: MouseEvent]
  rename: [version: string, e: MouseEvent]
  close: []
  setDropdownRef: [el: HTMLDivElement | null]
}>()

const renameLabel = (props.label && props.label.trim()) ? 'Edit label' : 'Add label'
const dropdownRef = ref<HTMLDivElement | null>(null)

// Send ref to parent for positioning
onMounted(() => {
  emit('setDropdownRef', dropdownRef.value)
})

onUnmounted(() => {
  emit('setDropdownRef', null)
})

useClickOutside({
  isActive: ref(true),
  refs: [dropdownRef],
  onClickOutside: () => emit('close'),
  additionalCheck: (target) => {
    const element = target as Element
    return !!element.closest?.('[data-actions]')
  },
})
</script>

<template>
  <Teleport to="#uifork-root">
    <div
      ref="dropdownRef"
      :class="styles.popover"
      data-popover-dropdown
      :style="{ visibility: 'hidden' }"
      role="menu"
    >
      <MenuItem
        :icon="RenameIcon"
        :label="renameLabel"
        :stop-propagation="true"
        @click="(e: MouseEvent) => { emit('rename', version, e); emit('close') }"
      />
      <MenuItem
        :icon="PromoteIcon"
        label="Promote"
        @click="(e: MouseEvent) => { emit('promote', version, e); emit('close') }"
      />
      <MenuItem
        :icon="OpenInEditorIcon"
        label="Open in editor"
        @click="(e: MouseEvent) => { emit('openInEditor', version, e); emit('close') }"
      />
      <div :class="styles.divider" />
      <MenuItem
        :icon="DeleteIcon"
        label="Delete"
        variant="delete"
        :stop-propagation="true"
        @click="(e: MouseEvent) => { emit('delete', version, e); emit('close') }"
      />
    </div>
  </Teleport>
</template>
