// packages/uifork-vue/src/components/NewVersionButton.vue
<script setup lang="ts">
import PlusIcon from './icons/PlusIcon.vue'
import styles from './UIFork.module.css'

defineProps<{
  disabled?: boolean
}>()

const emit = defineEmits<{
  click: [e: MouseEvent]
}>()
</script>

<template>
  <button
    @click="disabled ? undefined : emit('click', $event)"
    :class="[styles.newVersionButton, styles.menuItem, disabled ? styles.disabled : '']"
    :title="disabled ? 'Connect to server to create new versions' : 'Create new version'"
    :aria-disabled="disabled"
  >
    <div :class="styles.newVersionIconContainer">
      <PlusIcon :class="styles.newVersionIcon" />
    </div>
    <span>New version</span>
  </button>
</template>

// packages/uifork/src/components/NewVersionButton.tsx
import { PlusIcon } from "./icons/PlusIcon";
import styles from "./UIFork.module.css";

type NewVersionButtonProps = {
  onClick: (e: React.MouseEvent) => void;
};

export function NewVersionButton({ onClick }: NewVersionButtonProps) {
  return (
    <button
      onClick={onClick}
      className={`${styles.newVersionButton} ${styles.menuItem}`}
      title="Create new version"
    >
      <div className={styles.newVersionIconContainer}>
        <PlusIcon className={styles.newVersionIcon} />
      </div>
      <span>New version</span>
    </button>
  );
}
