// packages/uifork-vue/src/components/VersionActionMenu.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import styles from './UIFork.module.css'
import PromoteIcon from './icons/PromoteIcon.vue'
import OpenInEditorIcon from './icons/OpenInEditorIcon.vue'
import DeleteIcon from './icons/DeleteIcon.vue'
import RenameIcon from './icons/RenameIcon.vue'
import MenuItem from './MenuItem.vue'
import { useClickOutside } from '../composables/useClickOutside'

const props = defineProps<{
  version: string
  label?: string
}>()

const emit = defineEmits<{
  promote: [version: string, e: MouseEvent]
  openInEditor: [version: string, e: MouseEvent]
  delete: [version: string, e: MouseEvent]
  rename: [version: string, e: MouseEvent]
  close: []
  setDropdownRef: [el: HTMLDivElement | null]
}>()

const renameLabel = (props.label && props.label.trim()) ? 'Edit label' : 'Add label'
const dropdownRef = ref<HTMLDivElement | null>(null)

// Send ref to parent for positioning
onMounted(() => {
  emit('setDropdownRef', dropdownRef.value)
})

onUnmounted(() => {
  emit('setDropdownRef', null)
})

useClickOutside({
  isActive: ref(true),
  refs: [dropdownRef],
  onClickOutside: () => emit('close'),
  additionalCheck: (target) => {
    const element = target as Element
    return !!element.closest?.('[data-actions]')
  },
})
</script>

<template>
  <Teleport to="#uifork-root">
    <div
      ref="dropdownRef"
      :class="styles.popover"
      data-popover-dropdown
      :style="{ visibility: 'hidden' }"
      role="menu"
    >
      <MenuItem
        :icon="RenameIcon"
        :label="renameLabel"
        :stop-propagation="true"
        @click="(e: MouseEvent) => { emit('rename', version, e); emit('close') }"
      />
      <MenuItem
        :icon="PromoteIcon"
        label="Promote"
        @click="(e: MouseEvent) => { emit('promote', version, e); emit('close') }"
      />
      <MenuItem
        :icon="OpenInEditorIcon"
        label="Open in editor"
        @click="(e: MouseEvent) => { emit('openInEditor', version, e); emit('close') }"
      />
      <div :class="styles.divider" />
      <MenuItem
        :icon="DeleteIcon"
        label="Delete"
        variant="delete"
        :stop-propagation="true"
        @click="(e: MouseEvent) => { emit('delete', version, e); emit('close') }"
      />
    </div>
  </Teleport>
</template>

// src/components/VersionActionMenu.tsx
import React from "react";
import styles from "./UIFork.module.css";
import { PromoteIcon } from "./icons/PromoteIcon";
import { OpenInEditorIcon } from "./icons/OpenInEditorIcon";
import { DeleteIcon } from "./icons/DeleteIcon";
import { RenameIcon } from "./icons/RenameIcon";

interface VersionActionMenuProps {
  version: string;
  position: { x: number; y: number };
  onPromote: (version: string, e: React.MouseEvent) => void;
  onOpenInEditor: (version: string, e: React.MouseEvent) => void;
  onDelete: (version: string, e: React.MouseEvent) => void;
  onRename: (version: string, e: React.MouseEvent) => void;
  onClose: () => void;
  setDropdownRef: (el: HTMLDivElement | null) => void;
}

export function VersionActionMenu({
  version,
  position,
  onPromote,
  onOpenInEditor,
  onDelete,
  onRename,
  onClose,
  setDropdownRef,
}: VersionActionMenuProps) {
  return (
    <div
      ref={setDropdownRef}
      className={styles.popover}
      style={{
        left: `${position.x}px`,
        top: `${position.y}px`,
        visibility: "hidden",
      }}
      role="menu"
    >
      <button
        onClick={(e) => {
          onPromote(version, e);
          onClose();
        }}
        className={styles.popoverMenuItem}
      >
        <PromoteIcon className={styles.popoverMenuItemIcon} />
        <span>Promote</span>
      </button>
      <button
        onClick={(e) => {
          onOpenInEditor(version, e);
          onClose();
        }}
        className={styles.popoverMenuItem}
      >
        <OpenInEditorIcon className={styles.popoverMenuItemIcon} />
        <span>Open in editor</span>
      </button>
      <button
        onClick={(e) => {
          e.stopPropagation();
          onDelete(version, e);
          onClose();
        }}
        className={`${styles.popoverMenuItem} ${styles.popoverMenuItemDelete}`}
      >
        <DeleteIcon className={styles.popoverMenuItemIcon} />
        <span>Delete</span>
      </button>
      <button
        onClick={(e) => {
          e.stopPropagation();
          onRename(version, e);
          onClose();
        }}
        className={styles.popoverMenuItem}
      >
        <RenameIcon className={styles.popoverMenuItemIcon} />
        <span>Rename</span>
      </button>
    </div>
  );
}
